## Strategy Proposed:

- **See if the posts cluster**, and look on the topics or ideas they do (embedddings/vectorizers proposed: MixSpread from Ollama, Doc2Vec, Tf_IDF vectorizer)
  - Check the relationship with states and party affiliation
- **POS tagging** to identify verbs, adjectives, and modifiers (we can add a few more "word types" if we believe they are relevant)
  - Use them to identify potential "biased" ones and see if they are used more by certain states or party affiliation
  - See if the biased ones are linked to specific labels (here we use only the labeled data)
- **There are models that already check biases** and other important aspects on texts and political texts, we can explore using them and see what we get
  - Potential problem: our texts are more "impartial" than what they were probably trained on
- **Other ideas** if we see they are fit after the above exploration:
  - Polarity bias detection (probably too naive for how impartial our texts should be)
  - Disclosure Analysis
  - Image Clustering (I have a pipeline set up, but getting the data is something we have to explore)
  - I have a paper that presents an unsupervised deep learning technique that learns latent political ideologies from social media text to predict user political leaning -- we can see, it shouldn't work on our data but if it does, it is a problem. Other findings may arise from this.